name: yq_flutter
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
#version: 1.0.0+1
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
#  shared_preferences: "^0.4.1"
  event_bus: "^1.0.1"
#  日历
  flutter_cupertino_date_picker: "^0.3.0"
#  适配
  flutter_screenutil: ^0.3.0
#  ！！！
  dio: ^1.0.4
#  package_info: ^0.3.2
#  rxDrat
  rxdart: ^0.20.0
  json_annotation: ^2.0.0

  flutter_easyrefresh: ^1.2.5
#  device_info: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - images/about_us_icon.png
      - images/iv_dingdan.png
      - images/iv_coupon.png
      - images/iv_seastar.png
      - images/iv_user_customer.png
      - images/iv_setting.png
      - images/iv_arrow_right.png
      - images/mine_decoration_shape.png
      - images/close_btn.png
      - images/common_back_icon.png
      - images/refreshing.gif
      - images/iv_coupon_usetips.png
      - images/item_coupon_arow.png
      - images/item_disable_coupon_icon.png
      - images/item_coupon_expire.png
      - images/common_empty_icon.png
      - images/avatar_default_icon.png
      - images/agreement_checked.png
      - images/complete_info_floating_bg.png
      - images/coupon_item_right_bg.png
      - images/coupon_item_left_red_bg.png
      - images/coupon_item_left_gray_bg.png
  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidPackage: com.example.yqflutter
    iosBundleIdentifier: com.example.yqFlutter
